spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  cloud:
    compatibility-verifier:
      enabled: false
    openfeign:
      client:
        config:
          user-service:
            url: http://localhost:8081

server:
  port: 8082

springdoc:
  swagger-ui:
    path: /api-docs.html
    enabled: true
  api-docs:
    path: /api-docs
    enabled: true
  packages-to-scan: com.andersonsilva.taskservice.adapter.inbound.controller